### ISSUE TITLE
Savegame site loading is blank except for the loading bar

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#15]
Maybe the page appearance can be improved a bit

**Comment by crschnick** [comment]
For example, we could render an empty map or a 1444 map while it is loading.

**Comment by nickbabcock** [comment]
Map rendering is not performant enough and would cause the progress bar to stutter and delay the load of the save further. If the map was further optimized, I could see this as a potential solution.

**Comment by crschnick** [comment]
Define optimized. In a scenario like this, the map would be non interactive, i.e. not pannable etc., so it would only perform one rendering pass. The map resource loading can be done before the savegame load

**Comment by nickbabcock** [comment]
> Define optimized. In a scenario like this, the map would be non interactive, i.e. not pannable etc.,

On my computer setting up the renderer (linking shaders, bitmapping textures) takes 500ms which by the time that time has elapsed the save is just about done parsing and there would be minimal benefit. If we can get that time beneath 100ms or maybe even 250ms then it is worth considering.

> The map resource loading can be done before the savegame load

I don't believe this is feasible as more game maps are supported.

**Comment by crschnick** [comment]
You can put a spinning rakaly logo in the center of the loading page

**Comment by nickbabcock** [comment]
Any constant animations (like a loading symbol) are severely effected by map rendering (probably because all the GPU bandwidth is gone), and may cause the animation to stop. A stopped animation may be worse than no animation. I'm not opposed to the idea of sprucing up the loading save page, but it'd either need to be static content with no animations or when map rendering is less of a bottleneck.

**Comment by crschnick** [comment]
Then make the logo not spinning, still better than an empty page
