### ISSUE TITLE
Add battle locations mapmode

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#49]
Looks like the dev mapmode, but instead counts the amount of battles that have taken place in that province until now.

**Comment by nickbabcock** [comment]
I think this proposal needs a bit more substance.

The dev map mode is currently from red to green. Are you proposing to use that same gradient or use a gradient like gray to red, with red signalling many battles?

Is it envisioned for there to be a battle casualties map mode? How will users know that one map mode is for the count and the other is for casualties (as I'm assuming that these two map modes can differ significantly over the course of the game when battles can be fewer but more deadly)? Using map mode tooltips may adequately solve the problem, but I'm not sure as the existing map modes are analogous to their EU4 counterparts. Will sea tiles be included for naval battles / casualties?

Do you have any icon proposals for the new map mode?

How will the country filter interact with this map mode? As when there is a filter enabled, how should we determine what battles and provinces need to be included. Some variations I can think of off the top of my head:

- Include only provinces owned by a filtered country at the save date
- Include only provinces that had a battle with a filtered country
- Include only provinces that had a battle in a war while a filtered country was a participant
- Include only provinces that had a battle in a war where a filtered country is the original attacker / defender.

Once province inclusion is computed for filter, what is the logic for counting battles? Is it battles that involved at least one filtered country or is all battles during the time a filtered country was a participant in a war 

(note to self: for the ideas that involve looking at tags at a past date -- tag switches will need to be computed so that battles under a previous tag are carried forth).

**Comment by crschnick** [comment]
- same gradient as dev mapmode
- maybe instead of battle count use casualty count to take important battles more into consideration
- no naval battles
- icon can be thought of in the end
- filter should include only provinces owned by a filtered country at the save date
- I think all battles should be included as its easier. It may get a little bit falsified when third party wars are fought in your land, but overall it should still be insightful
